# AUTOGENERATED! DO NOT EDIT! File to edit: 05_transfer_learning.ipynb.

# %% auto 0
__all__ = ['download_blob_git']

# %% 05_transfer_learning.ipynb 3
import zipfile,requests,os
from pathlib import Path

def download_blob_git(url:str,file_name:str):
    """Downloads the blob or zip file from github rawlink. Only if file doesn't exist, if not simply exists.

    Args:
    url: Raw link need to be given, should have raw word in the link,rightclick raw option on github and copy link address.
    file_name: A name to be stored for that files in data folder should be same as github name

    Returns:
    None, Unzips the file and removes the zipped file. 
    """
    fpath=file_name
    image_path=Path(f'data/{fpath}')
    print(image_path)
    if image_path.is_file():
        print('Already exists skipping download')
    else:
        print('File doesnot exist downloading it')
        image_path.mkdir(parents=True,exist_ok=True)

        with open(f'data/{fpath}.zip','wb') as f:
            request=requests.get(url)
            print('Downloading the file')
            f.write(request.content)
        with zipfile.ZipFile(f'data/{fpath}.zip','r') as z:
            print('Unzipping the files')
            z.extractall(image_path)
        os.remove(f'data/{fpath}.zip')
